name: backend-integrator-projet CI

on: push

jobs:
  backend-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Premiere etape
        run: echo "premiere etape okkk"
      # - name: Installation des dependences
      #   run: mvn clean install
      # - name: Tests
      #   run: mvn test