name: backend-integrator-projet CI

on: push

jobs:
  backend-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Production repository
        uses: actions/checkout@v2
      - name: Setup maven
        uses: actions/setup-maven@v2
      # - name: Installation des dependences
      #   run: mvn clean install
      # - name: Tests
      #   run: mvn test